print_info() {
    info title
    info underline
    info distro
    info host
    info kernel
    info uptime
    info packages
    info shell
    info de
    info wm
    info term
    info memory
    info cols
}

kernel_shorthand="on"
uptime_shorthand="on"
memory_percent="on"
package_managers="on"
shell_version="on"
speed_type="bios_limit"
cpu_brand="on"
cpu_cores="logical"
gpu_brand="on"
gpu_type="all"
refresh_rate="on"
ascii_distro="arch_small"
ascii_colors=(distro)
colors=(distro)
bold="on"
