brew "neovim"
brew "lazygit"
#brew "clangd"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"
brew "zoxide"
brew "zsh"
brew "yazi"
#brew "ranger"
brew "tmux"
brew "tree"
brew "gh"
brew "llvm" # clang
brew "unzip"
brew "zip"
brew "npm"
brew "dotnet"
