github.com:
    git_protocol: https
    users:
        knotsolucky:
            oauth_token: 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
    user: knotsolucky
    oauth_token: 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
