# Use monitor = , to apply to all outputs.
# Keep the wallpaper file in ~/.config/HyprPaper/ to stay inside dotfiles flow.
wallpaper {
  monitor = DP-1
  path = ~/.config/wallpaper/wallpaper1.jpg
  fit_mode = cover
}
