local m = vim.keymap.set

m("n", ";", ":", { desc = "Command mode" })
m("i", "jk", "<Esc>", { desc = "Escape" })
m("n", "<leader>w", "<cmd>w<cr>", { desc = "Save" })
m("n", "<leader>q", "<cmd>q<cr>", { desc = "Quit" })
m("n", "<leader>e", "<cmd>NvimTreeToggle<cr>", { desc = "File tree" })
m("n", "<Tab>", "<cmd>bnext<cr>", { silent = true, desc = "Next buffer" })
m("n", "<S-Tab>", "<cmd>bprevious<cr>", { silent = true, desc = "Previous buffer" })
m("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer" })
m("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Previous buffer" })
m("n", "<leader>bd", "<cmd>bdelete<cr>", { desc = "Close buffer" })
m("n", "<leader><leader>", function()
  require("telescope.builtin").find_files({ cwd = vim.fn.expand("~") })
end, { desc = "Find files (home)" })
m("n", "<leader>ff", "<cmd>Telescope find_files<cr>", { desc = "Find files" })
m("n", "<leader>fr", "<cmd>Telescope oldfiles<cr>", { desc = "Recent files" })
m("n", "<leader>fg", "<cmd>Telescope live_grep<cr>", { desc = "Live grep" })
m("n", "<leader>fb", "<cmd>Telescope buffers<cr>", { desc = "Buffers" })
m("n", "<leader>fh", "<cmd>Telescope help_tags<cr>", { desc = "Help tags" })
m("n", "<leader>fy", "<cmd>Telescope resume<cr>", { desc = "Resume" })
m("n", "<leader>tt", function()
  require("transparent").toggle()
end, { desc = "Transparency mode" })
m("n", "<leader>th", "<cmd>Themery<cr>", { desc = "Theme switcher" })
m("n", "<leader>d", "<cmd>Alpha<cr>", { desc = "Dashboard" })
m("n", "<leader>ss", "<cmd>Telescope persisted<cr>", { desc = "Sessions" })
