vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<cr>", { desc = "Clear search highlight" })
vim.keymap.set("n", "gl", vim.diagnostic.open_float, { desc = "Diagnostic float" })
vim.keymap.set("n", "[d", function()
  vim.diagnostic.goto_prev({ float = true })
end, { desc = "Previous diagnostic" })
vim.keymap.set("n", "]d", function()
  vim.diagnostic.goto_next({ float = true })
end, { desc = "Next diagnostic" })
vim.keymap.set("n", "<leader>xl", vim.diagnostic.setqflist, { desc = "Diagnostics quickfix" })
vim.keymap.set("n", "<leader>cm", "<cmd>Mason<cr>", { desc = "Mason (LSP/DAP/lint/format)" })
